=== GaryJones/genesis-child-theme-index/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Genesis Child Theme",
	"description": "A theme entry in the Genesis Child Theme Index",
	"type": "object",
	"properties": {
		"name": {
			"description": "Name of the theme",
			"type": "string"
		},
		"author": {
			"description": "Name of the individual or company who is credited as the author of the theme",
			"type": "string"
		},
		"purchaseUrl": {
			"description": "The URL of the page where the theme can be purchased from, or in the case of being free, downloaded from",
			"type": "string"
		},
		"demoUrl": {
			"description": "The URL where a demo of the theme can be found",
			"type": "string"
		},
		"free": {
			"description": "True if the theme is free, false if a premium theme",
			"type": "boolean"
		},
		"html5": {
			"description": "True if the theme supports HTML5, false if it outputs XHTML instead",
			"type": "boolean"
		},
		"responsive": {
			"description": "True if the theme displays well at various screen sizes, false if it is fixed width",
			"type": "boolean"
		},
		"mobileMenu": {
			"description": "True if the theme displays a mobile-specific menu at small screen sizes, false if it doesn't",
			"type": "boolean"
		},
		"layouts": {
			"description": "The number of layouts the theme supports (Genesis default is 6 but child theme may register or register others)",
			"type": "integer",
			"minimum": 1
		},
		"accessibilityReady": {
			"description": "True if the theme meets all of the guidelines at http://make.wordpress.org/themes/guidelines/guidelines-accessibility/, false if not",
			"type": "boolean"
		},
		"customBackground": {
			"description": "True if the theme supports the WordPress custom background feature, false if it doesn't",
			"type": "boolean"
		},
		"customColors": {
			"description": "True if the theme allows a user to choose custom colors via an interface, false if it doesn't",
			"type": "boolean"
		},
		"editorStyle": {
			"description": "True if the theme includes styles for the post editor that match the front-end, false if it doesn't",
			"type": "boolean"
		},
		"featuredImageHeader": {
			"description": "True if the theme displays a featured image as a header, false if it doesn't.",
			"type": "boolean"
		},
		"grunt": {
			"description": "True if the theme includes support for *grunt* to allow development tasks to be automated, false if it doesn't",
			"type": "boolean"
		},
		"postFormats": {
			"description": "List of post formats the theme supports, `false` if it doesn't support any.",
			"oneOf": [
				{
					"type": "boolean",
					"enum": [
						"false"
					]
				},
				{
					"type": "array",
					"uniqueItems": true,
					"minItems": 1,
					"maxItems": 9,
					"items": {
						"type": "string",
						"enum": [
							"aside",
							"audio",
							"chat",
							"gallery",
							"image",
							"link",
							"quote",
							"status",
							"video"
						]
					}
				}
				
			]
		},
		"parallax": {
			"description": "True if the theme design includes a parallax feature, false if it doesn't",
			"type": "boolean"
		},
		"psds": {
			"description": "True if the theme includes PhotoShop (PSD) files of the original design, false if it doesn't",
			"type": "boolean"
		},
		"rtlLanguageSupport": {
			"description": "True if the theme includes right-to-left (RTL) style sheets, false if it doesn't",
			"type": "boolean"
		},
		"starter": {
			"description": "True if the theme author considers this theme to be a starter theme, false if not",
			"type": "boolean"
		},
		"translationReady": {
			"description": "True if the theme has all strings internationalised, loads a child theme text domain, and includes a .pot file, false if it doesn't",
			"type": "boolean"
		},
		"browsersSupported": {
			"title": "Browsers",
			"description": "Key-value pairs of browser names and their minimum supported versions",
			"type": "object",
			"properties": {
				"Chrome": {
					"type": "number"
				},
				"Firefox": {
					"type": "number"
				},
				"IE": {
					"type": "number"
				},
				"Opera": {
					"type": "number"
				},
				"Safari": {
					"type": "number"
				}
			}
		},
		"pluginsSupported": {
			"description": "List of plugins names that the theme explicitly includes styles for",
			"type": "array",
			"items": {
				"type": "string"
			},
			"uniqueItems": true
		}
	},
	"required": ["name", "author", "purchaseUrl"]
}

=== GaryJones/genesis-child-theme-index/themes/gary-jones_incipio-test.json
{
    "name": "Incipio (Test File)",
    "author": "Gary Jones, Gamajo Tech",
    "purchaseUrl": "http://shop.example.com/incipio/",
    "demoUrl": "http://demo.example.com/incipio/",
    "free": false,
    "html5": true,
    "responsive": true,
    "mobileMenu": true,
    "layouts": 6,
    "accessibilityReady": false,
    "customBackground": true,
    "customColors": false,
    "editorStyle": true,
    "featuredImageHeader": true,
    "grunt": true,
    "parallax": false,
    "postFormats": [
        "aside",
        "gallery"
    ],
    "psds": false,
    "rtlLanguageSupport": true,
    "starter": true,
    "translationReady": true,
    "browsersSupported": {
        "IE": 8,
        "Chrome": 22,
        "Safari": 6,
        "Firefox": 12
    },
    "pluginsSupported": [
        "WooCommerce",
        "bbPress",
        "Simple Social Icons"
    ]
}

=== GaryJones/genesis-child-theme-index/clvnk_minny.json
{
    "name": "Minny",
    "author": "CLVNK, Co.",
    "purchaseUrl": "http://demo.clvnk.co/minny/",
    "demoUrl": "http://demo.clvnk.co/minny/",
    "free": true,
    "html5": true,
    "responsive": true,
    "mobileMenu": false,
    "layouts": 1,
    "accessibilityReady": false,
    "customBackground": false,
    "customColors": false,
    "editorStyle": false,
    "featuredImageHeader": true,
    "grunt": false,
    "parallax": false,
    "postFormats": [
        "image",
        "quote",
        "link"
    ],
    "psds": false,
    "rtlLanguageSupport": false,
    "starter": false,
    "translationReady": false,
    "browsersSupported": {
        "IE": 8,
        "Chrome": 25,
        "Firefox": 3.6,
        "Opera": 12.4,
        "Safari": 5.1
    },
    "pluginsSupported": [
        "Simple Social Icons"
    ]
}
